### ISSUE TITLE
High DPI / 4k issue

### ISSUE THREAD

**Issue by Smorgan05** [darktrojan/newtabtools#178]
For high dpi or 4k monitors if you have New Tab Tools running you will see each picture in the tiles will not take up the full amount of the tile.  At most the Tile has about 25% to 30% because of the scaling of the picture.  This means we need an option to scale up the resolution of the tile to roughly 1200 by 440 pixels.  I would say at this point the current takes up about 500 by 290 pixels for the tile on 4k.  This shows the issue on the scaling side.

**Comment by darktrojan** [comment]
I don't really have anything to do with the thumbnail creation code, but New Tab Tools does try to set the prefs `toolkit.pageThumbs.minWidth`/`minHeight` to twice the size of your thumbnails, instead of the stupidly small default values. You can stop it doing that (set `extensions.newtabtools.thumbs.prefs.delay` to -1) and try your own values if you like. Unhelpfully Firefox caches the values when it first uses them, so you'll have to restart each time you make a change.

**Comment by Smorgan05** [comment]
After some poking around it seems that there is an automatic scaller within Firefox.  This means that even as you up the pixel count manually the image will get smaller.   I actually upped it to around 3000 by 800 and the result is hilarious aka basically you can't see a thing at that point.  I wish I could scale it with css to make it go to 100% instead of the integer based one or use a ratio to make it happen to autocenter it.

**Comment by despecial** [comment]
This has to be fixed. Cannot use it on a retina display.
Any suggestions to get it done?
