### ISSUE TITLE
Reload default thumbnail

### ISSUE THREAD

**Issue by PhoneixS** [darktrojan/newtabtools#2]
Could you add a option to update the thumbnail with a capture from the page as show now?

**Comment by JaykeBird** [comment]
That'd be useful! For some reasons, for two sites I frequently visit, the thumbnail images never turned out right for them, so they were just black screens. I've been too lazy to take a screenshot of the pages themselves and apply it as a thumbnail, although it really isn't too much effort, but a button that makes this happen in one click would be convenient.

**Comment by beautypersoni** [comment]
+1 This would be nice. Since last clearing my history, my pinned tiles are simply blank, even after using them to visit the links. Anyhoo...

**Comment by darktrojan** [comment]
You'll be able to do this from version 45, which is awaiting review.

**Comment by Eagle3386** [comment]
Minor problem: reloading stops at 302 redirects, i. e. all Google pages (GMail, Maps, Play Music and G+ tested so far) show "Moved temporarily" instead of the destination pages' image.

**Comment by darktrojan** [comment]
I had a look by going to docs.google.com, and found that the redirection is done by javascript, not HTTP 302. (Ew.) Even if that weren't the case, this sort of thing would be a bug in Mozilla's code, not mine.

**Comment by Eagle3386** [comment]
Thanks, Geoff, for digging that deep - I'll report this to Mozilla then. :)
