### ISSUE TITLE
Exclusion of domains/URLs

### ISSUE THREAD

**Issue by rugk** [darktrojan/newtabtools#213]
I propose to add a way to exclude certain URLs to appear on the new page at all.

For example as a web dev you may often visit `127.0.0.1`. However you really do not want to have that included in the new tab page as it is senseless if no web server is running and you do not really visit this page often, because you are interested in it's content, but because you need it for debugging (also with a lot of reloads).

So I would like to exclude `127.0.0.1`.

**Comment by d2inco** [comment]
i see that this is in the new release, but I don't see that it is working.  I added both my 'mailprovider.com' and '*.mailprovider.com' and set the limit to 1, but I still see two 'mailprovider.com' tiles in the non-pinned area .   Is this complete, yet?

**Comment by rugk** [comment]
Where can I add these domains?

**Comment by darktrojan** [comment]
@d2inco Currently the domain is exact-match only. So `subdomain.mailprovider.com` won't be excluded based on what you added. I'm changing this so that `.mailprovider.com` should hide both mailprovider.com and any subdomain.

@rugk In the options below "Tiles from your browsing history" is a button labelled Filter… which is what you need to click.

**Comment by spvkgn** [comment]
@darktrojan Is there a way to exclude domains in new NTT WebExtensions-based?
