### ISSUE TITLE
Things you can do if everything went wrong with your update

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#280]
Hello there, I make this thing. There was a major, *major*, update today, and something has gone wrong for a few people. If you're reading this, you're probably one of them.

First thing to note is this: even if I did understand exactly why your update has gone wrong *there's very little I can do about it*. I can't just make a new version that magically fixes everything and push it out to everybody today, because it doesn't work like that.

What I *do* know is:

- There's some mechanism in Firefox which controls the new tab page for extensions. This appears to be stuffing up.
- Your new tab page will no longer be `about:newtab`. It will be `moz-extension://some-letters-and-numbers/newTab.xhtml`. I can't tell you what the letters and numbers are because they're different for everybody.

If you load a new tab and see this or something like it (maybe just the gear icon):
![about_newtab](https://user-images.githubusercontent.com/1540303/29814195-9894d25c-8d00-11e7-931e-282fab33e986.png)
… that's the Firefox new tab. You might not have seen it for a while if you're a long time NTT user.

I think this is what's happened to most people that have had problems. The best remedy I can think of is **uninstall New Tab Tools, quit and restart Firefox, then reinstall New Tab Tools**. I can't be certain that works, but it seems to work for some people. You could also try starting Firefox with the `purgecaches` argument like this: `path\to\firefox.exe -purgecaches`.

Again, sorry this has happened. It's not my fault, and I can't magically fix it.

**EDIT: I've actually managed to reproduce some of the problems people have been reporting. Doing this will fix what I found:** (instructions for Windows because most people are on Windows)

1. Open the start menu.
2. Don't click on anything, just type `C:\Program Files\Mozilla Firefox\firefox.exe -purgecaches` (obviously if Firefox is somewhere else, type that location instead). Press enter.

**Comment by masterx1** [comment]
Is there a way to install an older version until firefox gets this fixed ?

**Comment by darktrojan** [comment]
Fair question, although I doubt it's going to get fixed. [Older versions.](https://addons.mozilla.org/firefox/addon/new-tab-tools/versions)

Also if you do succeed in making it work the problem shouldn't come back.

**Comment by masterx1** [comment]
Hmmmm. I installed version 81 and worked perfectly as usual. I tried 82.1 again and got the same problem.

**Comment by Erroneuz** [comment]
I can confirm it works with v81, but not with v82.1, so it seems like the issues lies with the addon and not some update from Firefox. Also mine stopped working without no update of Firefox has happened.. I'm running Firefox 55.0.3 64bit and the 0.3 update was installed last weekd.

**Comment by FlorianRem** [comment]
Hmm, I guess I didn't get the problem as the other users above. I just lost the custom images I had made for each of the links, but the links are still active and the layout unchanged. For those in my case, just reset all of the pictures and everything will work fine.

**Comment by darktrojan** [comment]
@FlorianRem Yes, working on that right now. That's an actual bug I can do something about. I'm going to try to put out a new version ASAP with a fix for that.

**Comment by GDZed** [comment]
v81 works for me too.

**Comment by darktrojan** [comment]
@masterx1 @GDZed @Erroneuz I *know* version 81 works. This information is not helpful.

**Comment by Alukah** [comment]
I went back to v81 as the URL being filled with random stuff makes the tool more of an inconvenience than what it helps, also disabled auto updates, has Mozilla said anything about allowing extensions to use about:blank? Will v81 work fine or does Mozilla have plans to fully disable all old extensions?

**Comment by darktrojan** [comment]
Okay, for those following along at home, there are some new instructions at the end of the first comment on this page. Go try them, and hopefully they will solve the whole "not starting" thing.

**Comment by alxpl** [comment]
For those complaining about the moz-extension:// prefix in the address bar, you can direct your input over at mozilla's bugzilla, the relevant bugs are [#1365355](https://bugzilla.mozilla.org/show_bug.cgi?id=1365355) & [#1322304](https://bugzilla.mozilla.org/show_bug.cgi?id=1322304).

**Comment by Erroneuz** [comment]
darktrojan I tried those instructions, which didn't work for me. So that's why I went back to v81 and to inform you, because the original post let on the problem was with Firefox, when it seems like it's with the latest version of the addon.

**Comment by Erroneuz** [comment]
Btw. seems like Ublock was hit by something similar today:

https://www.reddit.com/r/firefox/comments/6wl7t9/ublock_just_stopped_working_all_of_a_sudden/

Maybe this bug is related to this https://github.com/gorhill/uBlock/releases/tag/1.13.10

**Comment by XPJ38** [comment]
Well I was hit by the bug. I did manage to recover my NTT page whenever I open up a new tab with the _purgecaches_ trick, but I can't seem to load it when starting Firefox, even if I set the moz-extension:// URL as my home page in the settings. When I launch FF, a white page is displayed instead of NTT. Any idea why?

**Comment by Djsuperman** [comment]
I'm on Firefox 55.0.3 64-bit, and uninstalling, and reinstalling worked for me.

**Comment by bryce-lynch** [comment]
Just FYI, I've tried the purgecaches option and also reinstalled NTT, but the moz-extension:// is still there (using FF 55.0.3 / linux).

**Comment by FlorianRem** [comment]
Thanks for the fix! Everything is back in order for me now :)

**Comment by rgoldhor** [comment]
Darktrojan: I followed your suggestions: -purgecache did not work; removing and reinstalling DID work. 

Thanks for the quick response!

**Comment by gunthertoo** [comment]
Do you have any quick fix for ubuntu / linux ? I noticed this happening and the only way I could bring any tiles back was to go in the New Tab Tools settings and choose both "Tiles from your browsing history" and "Recently closed tabs." This is not how I usually have it set up and would appreciate a fix. Thanks.

**Comment by darktrojan** [comment]
Same thing, except you'll need to open a Terminal window to type `/path/to/firefox -purgecaches`.

**Comment by yuhler** [comment]
I think we have two different issues here, none of them of darktrojan's fault. My problem occurred after FF v55 update which messed NTT, uBlock Origin (but not uMatrix), and MAFF. Downgrading to FF v52 contributed to regain control of both uBlock and MAFF, but not NTT.
The problem is that FF disabled NTT and I found no way to re-enable it. FF refuses to re-install NTT because "it is not compatible with FF 55.0.2" though it runs perfectly in my WinXP tower. ANYWAY, this morning it did not block the install and NTT is back again to service! Last night I did some cleaning wiping \temp and \cache directories, and that may have helped, but I can't say for sure.
Last but not least I'll stick with FF v52 despite update warnings. I'll think on updates only upon Secunia PSI advice's or when FF broke something. This v55 update cost me almost a day of work.

**Comment by SteveSBE** [comment]
For what it's worth...

I kept getting FF's new tab instead of New Tab Tool's new tab in Windows 10 64 bit running FF 55.0.3 64 bit. It would work properly if I disabled the Tab Mix Plus add-on. However I like both add-ons. 

After some experimentation I got NTT and Tab Mix Plus to work at the same time by doing the following:
1. Disabled all add-ons. 
2. Removed the NTT add-on.
3. Restarted FF using command C:\Program Files\Mozilla Firefox\firefox.exe -purgecaches.
4. Reinstalled NTT v83.
5. Using about:config found the moz-extension://some-letters-and-numbers/newTab.xhtml so that we could do step 6. 
6. Using about:config ensured that the values were changed to moz-extension://some-letters-and-numbers/newTab.xhtml for any new tab url referencees (...newtab.url, ...taburl, etc.) or any other reference to default tabs that seemed to be those we would want to have the NTT tab.
7. Restarted FF using command C:\Program Files\Mozilla Firefox\firefox.exe -purgecaches.

There was a minor issue in that the tab that displays when I restarted FF was blank. I resolved that but cannot remember how I did so (sorry). 

Hope this helps.

Steve
