### ISSUE TITLE
what happened to my saved sites in new tab control

### ISSUE THREAD

**Issue by gunthertoo** [darktrojan/newtabtools#286]
Hi; first of all would like to thank you for this great extension. However,  something happened tonight when I clicked on a new tab it only came up with a few recent sites instead of my saved sites. There was also only a few options when I clicked the settings button, instead of the regular dialogue with options for add/removing pages. I'm not sure what has happened but where are my saved sites on my new tab page? :(

**Comment by rgoldhor** [comment]
Ditto here. All of a sudden this add-on (extension?) to Firefox is not active. Disabling and re-enabling it has no effect. The "new tab" display that I see when I open a new Firefox tab appears to be the built-in Firefox new tab display. So it would appear that your code never gets invoked, or exits due to an error condition, or some such thing.

Exiting and re-launching Firefox does not correct this condition.

Rebooting Windows does not correct this condition.

I am running Windows 7 Pro SP 1, running New Tab Tools 82.2 (Updated August 30, 2017), under Firefox 55.0.3 (32 bit).

**Comment by darktrojan** [comment]
Please read #280.

**Comment by gunthertoo** [comment]
Thanks darktrojan; worked like a charm!
