### ISSUE TITLE
Pale Moon branch?

### ISSUE THREAD

**Issue by scorpion451** [darktrojan/newtabtools#304]
So I've been testing driving Pale Moon (aka firefox minus mozilla stupidity) and loving it, but one of the addons I find myself missing is new tab tools. Quickdial tools looks different and doesn't have filters and custom images and I don't like change so it sucks. X3

Any chance of branching off the old pre-webextensions code for Pale Moon?

**Comment by darktrojan** [comment]
I'm not really interested in Pale Moon and I don't have time to be going back to fix old code. That said, you can get v81 from AMO and modify the package to work in Pale Moon. You'll need to change install.rdf to add PM compatibility, and chrome.manifest to override newTab.xul instead of newTab.xhtml. As a bare minimum, that works (I just tried it), there's probably broken things, but I'm not going to be the one fixing them.
